// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrdZ66BNjokB-lYB8yJz6hIU5ZyMny3Rg',
    appId: '1:1045252634080:web:16f02a940f69378027e785',
    messagingSenderId: '1045252634080',
    projectId: 'batteryapp-3e3c5',
    authDomain: 'batteryapp-3e3c5.firebaseapp.com',
    storageBucket: 'batteryapp-3e3c5.appspot.com',
    measurementId: 'G-FYNCWHCMJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj5Wv90zUYHqsCPtA1Vhf98cxv2Fa50IA',
    appId: '1:1045252634080:android:517b95f35a7210b427e785',
    messagingSenderId: '1045252634080',
    projectId: 'batteryapp-3e3c5',
    storageBucket: 'batteryapp-3e3c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCtRk8Uf6BdRl92Z4oDhLG1_8CvWpelfQ',
    appId: '1:1045252634080:ios:66b200476720285627e785',
    messagingSenderId: '1045252634080',
    projectId: 'batteryapp-3e3c5',
    storageBucket: 'batteryapp-3e3c5.appspot.com',
    iosBundleId: 'com.example.batteryServiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCtRk8Uf6BdRl92Z4oDhLG1_8CvWpelfQ',
    appId: '1:1045252634080:ios:74ede26099c76dd827e785',
    messagingSenderId: '1045252634080',
    projectId: 'batteryapp-3e3c5',
    storageBucket: 'batteryapp-3e3c5.appspot.com',
    iosBundleId: 'com.example.batteryServiceApp.RunnerTests',
  );
}
